# Generated by Django 5.0.1 on 2024-03-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('emp_id', models.CharField(help_text='Employee ID', max_length=10)),
                ('emp_name', models.CharField(help_text='Employee Name', max_length=30)),
                ('emp_email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('emp_profile', models.ImageField(upload_to='')),
                ('emp_address', models.TextField()),
                ('emp_designation', models.CharField(choices=[('Admin', 'Admin'), ('CEO', 'CEO'), ('COO', 'COO'), ('Project Manager', 'Project Manager'), ('Jr. PHP Laravel Developer', 'Jr. PHP Laravel Developer'), ('Sr. Developer', 'Sr. Developer'), ('UI/UX Designer', 'UI/UX Designer'), ('Product Manager', 'Product Manager'), ('Quality Engineer', 'Quality Engineer'), ('Quality Engineer Lead', 'Quality Engineer Lead'), ('Web Designer', 'Web Designer'), ('Sr. Developer', 'Sr. Developer'), ('SEO Executive', 'SEO Executive'), ('Jr. HR Executive', 'Jr. HR Executive'), ('Jr. PHP Laravel Developer\t', 'Jr. PHP Laravel Developer'), ('Sr. HR Executive', 'Sr. HR Executive'), ('Sr. SEO Executive', '\tSr. SEO Executive'), ('Content Writer', 'Content Writer'), ('Jr.React Native Developer', 'Jr.React Native Developer'), ('Trainee', 'Trainee'), ('Tech Lead', 'Tech Lead'), ('Python Developer', 'Python Developer'), ('Jr. Web Designer', 'Jr. Web Designer'), ('Intern', 'Intern'), ('Lead Generation Executive', 'Lead Generation Executive')], help_text='Employee Designation', max_length=70)),
                ('emp_role', models.CharField(choices=[('Admin', 'Admin'), ('HR', 'HR'), ('Employee', 'Employee')], help_text='Employee Role', max_length=50)),
                ('emp_company', models.CharField(choices=[('PranshTech Solutions', 'PranshTech Solutions'), ('Textdrip', 'Textdrip')], help_text='Employee Company', max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
