# Generated by Django 5.0.3 on 2024-03-12 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_employee_emp_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_contact',
            field=models.CharField(default=9110718156, max_length=15),
            preserve_default=False,
        ),
    ]
